//! Your **faction** — an always-alive industrial swarm that plays the long game for you, even while
//! you are logged off.
//!
//! Every player owns a [`Faction`]: a base of buildings (harvesters, refineries, factories, shipyards,
//! turrets), a swarm of units (drones, fighters, haulers), a resource stockpile, and a tech list. The
//! faction runs a deterministic economy **every tick whether you are online or not**: buildings
//! generate and refine resources, the build queue advances, and — crucially — when the faction is idle
//! it **spends your resources for you**, picking the next most valuable build or upgrade from its
//! [`AutoPolicy`] and starting it. You come back to a bigger base, a larger swarm, and upgrades you
//! never had to click. Your faction is always alive.
//!
//! The whole thing is pure, deterministic, and serializable, so it is simulated on the sector host,
//! checkpointed into the sector snapshot, and kept as high-precision replicas on nearby nodes
//! ([`crate::replication`]) — if your host drops, your faction keeps building on the node that takes
//! over, without missing a tick.
//!
//! The build catalogue (costs, times, yields) is data here and can be lifted into the hot-reloadable
//! [`crate::ruleset::Ruleset`] so the economy can be re-balanced live like everything else.

use serde::{Deserialize, Serialize};
use std::collections::VecDeque;

/// The resource stockpile. Integers so the economy is exact and deterministic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct Resources {
    /// Mined from asteroids; the base input.
    pub minerals: u64,
    /// Generated by harvesters/solar; powers refining and factories.
    pub energy: u64,
    /// Refined from minerals + energy; the input to ships and high-tier buildings.
    pub alloys: u64,
}

impl Resources {
    pub fn new(minerals: u64, energy: u64, alloys: u64) -> Self {
        Resources { minerals, energy, alloys }
    }

    /// Can this stockpile pay `cost`?
    pub fn covers(&self, cost: &Resources) -> bool {
        self.minerals >= cost.minerals && self.energy >= cost.energy && self.alloys >= cost.alloys
    }

    /// Pay `cost` if affordable; returns true on success.
    pub fn try_spend(&mut self, cost: &Resources) -> bool {
        if !self.covers(cost) {
            return false;
        }
        self.minerals -= cost.minerals;
        self.energy -= cost.energy;
        self.alloys -= cost.alloys;
        true
    }

    pub fn add(&mut self, o: &Resources) {
        self.minerals = self.minerals.saturating_add(o.minerals);
        self.energy = self.energy.saturating_add(o.energy);
        self.alloys = self.alloys.saturating_add(o.alloys);
    }
}

/// A kind of building. Stats are returned by [`BuildingKind::stats`] so the catalogue is one place.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BuildingKind {
    /// Generates minerals each tick (more with level).
    Harvester,
    /// Converts minerals + energy into alloys each tick.
    Refinery,
    /// Generates energy each tick.
    Solar,
    /// Builds units (drones/fighters) faster; required to queue units.
    Factory,
    /// Builds the largest units; unlocks haulers/capitals.
    Shipyard,
    /// Defensive emplacement (no production; contributes to defense rating).
    Turret,
}

/// Per-building production / cost numbers.
#[derive(Debug, Clone, Copy)]
pub struct BuildingStats {
    pub cost: Resources,
    pub build_ticks: u64,
    /// Per-tick resource yield at level 1 (scaled by level). Negative inputs are consumed.
    pub yield_minerals: i64,
    pub yield_energy: i64,
    pub yield_alloys: i64,
    /// Inputs consumed per tick at level 1 to produce the yields (e.g. a refinery eats minerals).
    pub input_minerals: u64,
    pub input_energy: u64,
}

impl BuildingKind {
    pub fn stats(self) -> BuildingStats {
        match self {
            BuildingKind::Harvester => BuildingStats {
                cost: Resources::new(50, 0, 0),
                build_ticks: 60,
                yield_minerals: 4,
                yield_energy: 0,
                yield_alloys: 0,
                input_minerals: 0,
                input_energy: 0,
            },
            BuildingKind::Solar => BuildingStats {
                cost: Resources::new(40, 0, 0),
                build_ticks: 50,
                yield_minerals: 0,
                yield_energy: 5,
                yield_alloys: 0,
                input_minerals: 0,
                input_energy: 0,
            },
            BuildingKind::Refinery => BuildingStats {
                cost: Resources::new(80, 20, 0),
                build_ticks: 100,
                yield_minerals: 0,
                yield_energy: 0,
                yield_alloys: 2,
                input_minerals: 4,
                input_energy: 2,
            },
            BuildingKind::Factory => BuildingStats {
                cost: Resources::new(120, 40, 20),
                build_ticks: 160,
                yield_minerals: 0,
                yield_energy: 0,
                yield_alloys: 0,
                input_minerals: 0,
                input_energy: 0,
            },
            BuildingKind::Shipyard => BuildingStats {
                cost: Resources::new(300, 120, 120),
                build_ticks: 400,
                yield_minerals: 0,
                yield_energy: 0,
                yield_alloys: 0,
                input_minerals: 0,
                input_energy: 0,
            },
            BuildingKind::Turret => BuildingStats {
                cost: Resources::new(90, 30, 40),
                build_ticks: 120,
                yield_minerals: 0,
                yield_energy: 0,
                yield_alloys: 0,
                input_minerals: 0,
                input_energy: 0,
            },
        }
    }

    /// Cost to upgrade a building currently at `level` to the next (scales with level).
    pub fn upgrade_cost(self, level: u32) -> Resources {
        let base = self.stats().cost;
        let m = (level + 1) as u64;
        Resources::new(base.minerals * m, base.energy * m, base.alloys * m)
    }
}

/// A unit (member of the swarm) the faction can build.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UnitKind {
    /// Cheap swarm worker; mines and repairs.
    Drone,
    /// Combat escort.
    Fighter,
    /// Moves resources between bases; needs a shipyard.
    Hauler,
}

impl UnitKind {
    pub fn cost(self) -> Resources {
        match self {
            UnitKind::Drone => Resources::new(30, 10, 5),
            UnitKind::Fighter => Resources::new(60, 20, 30),
            UnitKind::Hauler => Resources::new(120, 40, 80),
        }
    }
    pub fn build_ticks(self) -> u64 {
        match self {
            UnitKind::Drone => 40,
            UnitKind::Fighter => 90,
            UnitKind::Hauler => 200,
        }
    }
    /// Shipyard required?
    pub fn needs_shipyard(self) -> bool {
        matches!(self, UnitKind::Hauler)
    }
    /// Hull of the NPC ship this unit becomes in the world.
    pub fn hp(self) -> i32 {
        match self {
            UnitKind::Drone => 30,
            UnitKind::Fighter => 90,
            UnitKind::Hauler => 140,
        }
    }
    /// Does this unit fight (carry a weapon)? Drones mine, haulers haul; fighters fight.
    pub fn is_combat(self) -> bool {
        matches!(self, UnitKind::Fighter)
    }
}

/// A standing order the player gives their faction — every NPC ship the faction owns obeys it. The
/// order persists with the faction (snapshotted/replicated), so your fleet keeps its instructions
/// across a host failover and while you are offline.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Default)]
#[serde(tag = "cmd", rename_all = "snake_case")]
pub enum FactionCommand {
    /// Guard the owner: drones mine nearby, fighters escort and engage anything that comes close.
    #[default]
    Defend,
    /// All ships converge on and stay near the owner.
    Follow,
    /// Drones seek asteroids; non-drones idle. Pure economy.
    Mine,
    /// Hold position — stop and wait.
    Hold,
    /// Fighters hunt the nearest enemy anywhere in the sector.
    AttackNearest,
    /// Move the fleet to a point, engaging enemies en route.
    AttackMove { x: f32, y: f32 },
}

/// A constructed building.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Building {
    pub kind: BuildingKind,
    pub level: u32,
    pub hp: i32,
}

/// A constructed unit.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Unit {
    pub kind: UnitKind,
    pub hp: i32,
}

/// What a build order is producing.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum BuildTarget {
    Building(BuildingKind),
    UpgradeBuilding(usize),
    Unit(UnitKind),
}

/// An in-progress build. The cost is paid up front when enqueued; `remaining` ticks down.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BuildOrder {
    pub target: BuildTarget,
    pub remaining: u64,
}

/// The autonomous policy the faction follows when idle — the brain that spends your resources for you.
/// It keeps the economy growing toward target ratios, then expands military. Pure: [`AutoPolicy::next`]
/// chooses the next build given the current faction state, or `None` if nothing useful is affordable.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AutoPolicy {
    pub want_harvesters: u32,
    pub want_solar: u32,
    pub want_refineries: u32,
    pub want_factories: u32,
    /// Once the economy targets are met, keep building this many fighters per factory before expanding.
    pub fighters_per_factory: u32,
    /// Build a shipyard once alloy income is comfortable.
    pub want_shipyard: bool,
    pub enabled: bool,
}

impl Default for AutoPolicy {
    fn default() -> Self {
        AutoPolicy {
            want_harvesters: 4,
            want_solar: 3,
            want_refineries: 2,
            want_factories: 2,
            // Keep the auto-built standing fleet modest — it should be a screen of escorts you grow into,
            // not an instant deathball. The player tops it up with explicit orders and earns more by
            // surviving raids; combined with marauder attrition this keeps the fleet dynamic, not maxed.
            fighters_per_factory: 3,
            want_shipyard: true,
            enabled: true,
        }
    }
}

impl AutoPolicy {
    /// Decide the next thing to build, in priority order: keep harvesters & solar up, then refineries,
    /// then factories, then a shipyard, then grow the fighter swarm, then upgrade the oldest building.
    /// Returns the target only if the faction can currently afford it (so the caller pays and enqueues).
    pub fn next(&self, f: &Faction) -> Option<BuildTarget> {
        if !self.enabled {
            return None;
        }
        let count = |k: BuildingKind| f.buildings.iter().filter(|b| b.kind == k).count() as u32;
        let afford_b = |k: BuildingKind| f.resources.covers(&k.stats().cost);
        let afford_u = |k: UnitKind| f.resources.covers(&k.cost());

        if count(BuildingKind::Harvester) < self.want_harvesters && afford_b(BuildingKind::Harvester) {
            return Some(BuildTarget::Building(BuildingKind::Harvester));
        }
        if count(BuildingKind::Solar) < self.want_solar && afford_b(BuildingKind::Solar) {
            return Some(BuildTarget::Building(BuildingKind::Solar));
        }
        if count(BuildingKind::Refinery) < self.want_refineries && afford_b(BuildingKind::Refinery) {
            return Some(BuildTarget::Building(BuildingKind::Refinery));
        }
        if count(BuildingKind::Factory) < self.want_factories && afford_b(BuildingKind::Factory) {
            return Some(BuildTarget::Building(BuildingKind::Factory));
        }
        if self.want_shipyard && count(BuildingKind::Shipyard) == 0 && afford_b(BuildingKind::Shipyard) {
            return Some(BuildTarget::Building(BuildingKind::Shipyard));
        }
        // Grow the swarm if we have factory capacity.
        let factories = count(BuildingKind::Factory);
        let fighters = f.units.iter().filter(|u| u.kind == UnitKind::Fighter).count() as u32;
        if factories > 0 && fighters < factories * self.fighters_per_factory && afford_u(UnitKind::Fighter) {
            return Some(BuildTarget::Unit(UnitKind::Fighter));
        }
        // Otherwise, sink resources into upgrading the cheapest-to-upgrade economy building.
        let mut best: Option<(usize, u64)> = None;
        for (i, b) in f.buildings.iter().enumerate() {
            if matches!(b.kind, BuildingKind::Turret) {
                continue;
            }
            let c = b.kind.upgrade_cost(b.level);
            if f.resources.covers(&c) {
                let total = c.minerals + c.energy + c.alloys;
                if best.map(|(_, t)| total < t).unwrap_or(true) {
                    best = Some((i, total));
                }
            }
        }
        best.map(|(i, _)| BuildTarget::UpgradeBuilding(i))
    }
}

/// A player's faction. Deterministic; serialized into snapshots and replicated.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Faction {
    /// Owning player NodeId.
    pub owner: String,
    pub resources: Resources,
    pub buildings: Vec<Building>,
    pub units: Vec<Unit>,
    pub queue: VecDeque<BuildOrder>,
    pub tech: Vec<String>,
    pub policy: AutoPolicy,
    /// The standing order every NPC ship of this faction obeys.
    #[serde(default)]
    pub command: FactionCommand,
    /// Monotonic id source for spawned NPC ships, so a destroyed ship's id is never reused.
    #[serde(default)]
    pub next_unit_seq: u64,
    /// Total ticks the faction has been simulated (advances whether the player is online or not).
    pub age_ticks: u64,
}

impl Faction {
    /// A fresh faction with a starter base: one harvester, one solar, a small stockpile.
    pub fn founding(owner: &str) -> Self {
        Faction {
            owner: owner.to_string(),
            resources: Resources::new(120, 60, 20),
            buildings: vec![
                Building { kind: BuildingKind::Harvester, level: 1, hp: 100 },
                Building { kind: BuildingKind::Solar, level: 1, hp: 100 },
            ],
            units: vec![Unit { kind: UnitKind::Drone, hp: 30 }],
            queue: VecDeque::new(),
            tech: Vec::new(),
            policy: AutoPolicy::default(),
            command: FactionCommand::default(),
            next_unit_seq: 0,
            age_ticks: 0,
        }
    }

    /// Allocate the next stable NPC ship id for this faction (`npc:<owner>:<seq>`). The owner prefix
    /// makes the id self-describing and the monotonic seq guarantees a destroyed ship's id is never
    /// reused.
    pub fn next_ship_id(&mut self) -> String {
        let id = format!("npc:{}:{}", self.owner, self.next_unit_seq);
        self.next_unit_seq += 1;
        id
    }

    /// Record the loss of one NPC ship of `kind` (its hull hit zero in the world). Returns true if a
    /// unit was removed from the roster.
    pub fn lose_unit(&mut self, kind: UnitKind) -> bool {
        if let Some(i) = self.units.iter().position(|u| u.kind == kind) {
            self.units.remove(i);
            true
        } else {
            false
        }
    }

    /// Count roster units of a kind (the desired number of live NPC ships of that kind).
    pub fn unit_count(&self, kind: UnitKind) -> usize {
        self.units.iter().filter(|u| u.kind == kind).count()
    }

    /// Manually enqueue a build (a player's explicit order). Pays the cost up front; returns false if
    /// unaffordable or disallowed (e.g. a hauler with no shipyard).
    pub fn enqueue(&mut self, target: BuildTarget) -> bool {
        let (cost, ticks) = match &target {
            BuildTarget::Building(k) => (k.stats().cost, k.stats().build_ticks),
            BuildTarget::UpgradeBuilding(i) => {
                let Some(b) = self.buildings.get(*i) else { return false };
                (b.kind.upgrade_cost(b.level), b.kind.stats().build_ticks)
            }
            BuildTarget::Unit(k) => {
                if k.needs_shipyard() && !self.buildings.iter().any(|b| b.kind == BuildingKind::Shipyard) {
                    return false;
                }
                if *k != UnitKind::Drone && !self.buildings.iter().any(|b| b.kind == BuildingKind::Factory) {
                    return false; // need a factory for combat units
                }
                (k.cost(), k.build_ticks())
            }
        };
        if !self.resources.try_spend(&cost) {
            return false;
        }
        // Factories speed up unit builds; more factories => shorter time.
        let ticks = if matches!(target, BuildTarget::Unit(_)) {
            let f = self.buildings.iter().filter(|b| b.kind == BuildingKind::Factory).count().max(1) as u64;
            (ticks / f).max(1)
        } else {
            ticks
        };
        self.queue.push_back(BuildOrder { target, remaining: ticks });
        true
    }

    /// Advance the faction one tick. **Runs every tick, online or offline.** Produces resources,
    /// advances the build queue, and — when idle — lets the [`AutoPolicy`] spend resources for the
    /// player automatically. This is the "always alive" loop.
    pub fn tick(&mut self) {
        self.age_ticks += 1;

        // 1) Production: each building yields/consumes per tick, scaled by level. A refinery only runs
        //    if its inputs are available.
        let mut gained = Resources::default();
        for b in &self.buildings {
            let s = b.kind.stats();
            let lvl = b.level.max(1) as i64;
            // Inputs first (skip production if unaffordable).
            let in_min = s.input_minerals * b.level.max(1) as u64;
            let in_en = s.input_energy * b.level.max(1) as u64;
            if in_min > 0 || in_en > 0 {
                if self.resources.minerals >= in_min && self.resources.energy >= in_en {
                    self.resources.minerals -= in_min;
                    self.resources.energy -= in_en;
                } else {
                    continue; // starved this tick
                }
            }
            if s.yield_minerals != 0 {
                gained.minerals = gained.minerals.saturating_add((s.yield_minerals * lvl).max(0) as u64);
            }
            if s.yield_energy != 0 {
                gained.energy = gained.energy.saturating_add((s.yield_energy * lvl).max(0) as u64);
            }
            if s.yield_alloys != 0 {
                gained.alloys = gained.alloys.saturating_add((s.yield_alloys * lvl).max(0) as u64);
            }
        }
        self.resources.add(&gained);

        // 2) Advance the active build order; complete it when it finishes.
        if let Some(front) = self.queue.front_mut() {
            front.remaining = front.remaining.saturating_sub(1);
            if front.remaining == 0 {
                let done = self.queue.pop_front().unwrap();
                self.complete(done.target);
            }
        }

        // 3) Idle autonomy: if nothing is building, let the policy spend resources for the player.
        if self.queue.is_empty()
            && let Some(target) = self.policy.next(self)
        {
            self.enqueue(target);
        }
    }

    fn complete(&mut self, target: BuildTarget) {
        match target {
            BuildTarget::Building(kind) => self.buildings.push(Building { kind, level: 1, hp: 100 }),
            BuildTarget::UpgradeBuilding(i) => {
                if let Some(b) = self.buildings.get_mut(i) {
                    b.level += 1;
                    b.hp += 25;
                }
            }
            BuildTarget::Unit(kind) => self.units.push(Unit { kind, hp: 30 }),
        }
    }

    /// A coarse strength rating (for matchmaking / leaderboards): buildings + units + upgrades.
    pub fn power(&self) -> u64 {
        let b: u64 = self.buildings.iter().map(|b| (b.level as u64) * 10).sum();
        let u: u64 = self
            .units
            .iter()
            .map(|u| match u.kind {
                UnitKind::Drone => 2,
                UnitKind::Fighter => 8,
                UnitKind::Hauler => 12,
            })
            .sum();
        b + u
    }

    /// Credit mined minerals into the faction stockpile — the bridge from the live arena (a player
    /// mining an asteroid) to the persistent economy.
    pub fn deposit_minerals(&mut self, amount: u64) {
        self.resources.minerals = self.resources.minerals.saturating_add(amount);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn founding_faction_has_a_starter_base() {
        let f = Faction::founding("nodeA");
        assert_eq!(f.owner, "nodeA");
        assert!(f.buildings.len() >= 2);
        assert!(f.power() > 0);
    }

    #[test]
    fn economy_produces_resources_over_time() {
        let mut f = Faction::founding("n");
        f.policy.enabled = false; // isolate production from autonomy
        let before = f.resources;
        for _ in 0..50 {
            f.tick();
        }
        assert!(f.resources.minerals > before.minerals, "harvester accrues minerals");
        assert!(f.resources.energy > before.energy, "solar accrues energy");
    }

    #[test]
    fn idle_faction_builds_for_you_while_away() {
        // The headline behaviour: with autonomy on and no player input, the faction grows itself.
        let mut f = Faction::founding("n");
        f.resources = Resources::new(2000, 2000, 2000); // a healthy stockpile to spend
        let b0 = f.buildings.len();
        for _ in 0..2000 {
            f.tick();
        }
        assert!(f.buildings.len() > b0, "the faction autonomously expanded its base");
        assert!(f.power() > Faction::founding("n").power(), "the faction got stronger while idle");
    }

    #[test]
    fn manual_order_is_paid_up_front_and_completes() {
        let mut f = Faction::founding("n");
        f.policy.enabled = false;
        f.resources = Resources::new(1000, 1000, 1000);
        let before = f.resources.minerals;
        assert!(f.enqueue(BuildTarget::Building(BuildingKind::Refinery)));
        assert!(f.resources.minerals < before, "cost paid up front");
        let ticks = BuildingKind::Refinery.stats().build_ticks;
        for _ in 0..ticks {
            f.tick();
        }
        assert!(f.buildings.iter().any(|b| b.kind == BuildingKind::Refinery), "refinery completed");
    }

    #[test]
    fn hauler_requires_a_shipyard() {
        let mut f = Faction::founding("n");
        f.resources = Resources::new(10_000, 10_000, 10_000);
        assert!(!f.enqueue(BuildTarget::Unit(UnitKind::Hauler)), "no shipyard -> rejected");
        f.buildings.push(Building { kind: BuildingKind::Shipyard, level: 1, hp: 100 });
        f.buildings.push(Building { kind: BuildingKind::Factory, level: 1, hp: 100 });
        assert!(f.enqueue(BuildTarget::Unit(UnitKind::Hauler)), "with a shipyard -> allowed");
    }

    #[test]
    fn faction_sim_is_deterministic() {
        let mut a = Faction::founding("n");
        let mut b = Faction::founding("n");
        a.resources = Resources::new(5000, 5000, 5000);
        b.resources = Resources::new(5000, 5000, 5000);
        for _ in 0..1500 {
            a.tick();
            b.tick();
        }
        assert_eq!(a, b, "same start + same ticks => identical faction (replication-safe)");
    }
}
